##############################################
# !!! Datei umbenennen !!!              ######
# secrets_copy.toml -> secrets.toml     ######
##############################################

# Credentials for WebDAV file storage such as SwitchDrive
[webdav]
base_url = "https://drive.switch.ch/remote.php/webdav/"
https://drive.switch.ch/index.php/apps/files/?dir=/&fileid=8901255078
username = laura.gjugja@gmail.com
password = WVNIW-WGNUN-RFXQF-EWHUT
